<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Authors>风尘WD(FengchenWD)</Authors>
    <Copyright>Copyright (c) 风尘WD(FengchenWD)</Copyright>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetLockFilePath Condition="'$(UsePublishLockFile)' == 'true'">$(MSBuildProjectDirectory)\packages.publish-win-x64.lock.json</NuGetLockFilePath>
  </PropertyGroup>
</Project>
